import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/themes/themes/catppuccin-latte.toml"
  "~/.config/alacritty/themes/themes/catppuccin-frappe.toml"
  # "~/.config/alacritty/themes/themes/catppuccin-macchiato.toml"
  # "~/.config/alacritty/themes/themes/catppuccin-mocha.toml"
]

[font]
size = 7.0

[font.bold]
family = "geist Mono Nerd Font"
# family = "HeavyData Nerd Font"
# family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "geist Mono Nerd Font"
# family = "HeavyData Nerd Font"
# family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "geist Mono Nerd Font"
# family = "HeavyData Nerd Font"
# family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "geist Mono Nerd Font"
# family = "HeavyData Nerd Font"
# family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.9
